export const type ={
    POST_USER : 'POST_USER',
    PUT_USER :'PUT_USER',
    GET_ALL_USER : 'GET_ALL_USER',
    GET_USER :'GET_USER',
    GET_LOGIN : 'GET_LOGIN',
    POST_GAME : 'POST_GAME',
    GET_GAME : 'GET_GAME',
    FILTER_BY_COUNTRY :'SORTED_BY_COUNTRY',
    SORTED_BY_POINTS: 'SORTED_BY_POINTS',
};  