const GET_USER = "GET_USER";
const ERROR = "ERROR";
const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const LOADING_USER = "LOADING_USER";
const LOADING_USER_AUTH = "LOADING_USER_AUTH";
const UPDATE_USER_ADMIN = "UPDATE_USER_ADMIN";

const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";

const GET_ALL_USERS = "GET_ALL_USERS";
const GET_BY_FILTERED = "GET_BY_FILTERED";
const ORDER_NAME = "ORDER_NAME"
const ORDER_POINTS = "ORDER_POINTS"

const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";

const GET_ALL_GAMES = "GET_ALL_GAMES"

const GET_ALL_PAYS = "GET_ALL_PAYS"

export {
  GET_USER,
  LOGIN_USER,
  LOGOUT_USER,
  ERROR,
  LOADING_USER,
  SHOW_ALERT,
  HIDE_ALERT,
  ORDER_POINTS,
  GET_ALL_USERS,
  GET_BY_FILTERED,
  ORDER_NAME,
  LOADING_USER_AUTH,
  GET_ALL_COUNTRIES,
  UPDATE_USER_ADMIN,
  GET_ALL_GAMES,
  GET_ALL_PAYS
};
