const GET_USER = "GET_USER";
const ERROR = "ERROR";
const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const LOADING_USER = "LOADING_USER";

const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";

export {
  GET_USER,
  LOGIN_USER,
  LOGOUT_USER,
  ERROR,
  LOADING_USER,
  SHOW_ALERT,
  HIDE_ALERT,
};
